name: composefree
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.13, 2.13.5]
    env:
      SCALA_VERSION: ${{ matrix.scala }}
    steps:
      - uses: actions/checkout@v2
      - name: sbt test
        run: sbt ++$SCALA_VERSION test
      - name: sbt example/run
        run: sbt ++$SCALA_VERSION example/run
      - name: sbt docs/mdoc
        run: sbt ++$SCALA_VERSION docs/mdoc
